### PR TITLE
Speed up dumpTree.py for larger files

### PR DESCRIPTION
**Pull request by peter-madigan**
Using a list to collect sub-arrays prior to concatenation scales much better for large-ish (~10k) EDepSim files.

### CODE REVIEW

**Comment by peter-madigan** [comment]
@soleti do you know why the docs failed? I didn't touch anything that should impact them...

**Comment by soleti** [comment]
@peter-madigan Uhm, weird. Can it have something to do with the new `larpix` requirements? It looks like it's failing to install `bitarray`?

**Comment by peter-madigan** [comment]
Ah could be. I should probably relax most the the requirements, I'll do
that tomorrow.

**Comment by soleti** [comment]
I think I fixed and in any case is not related to this PR

**Pull request merged**
