### PR TITLE
Save to file after each event

### PR DESCRIPTION
**Pull request by soleti**
This PR changes the way we save the result of the simulation to file by doing it after each event, and not at the end of the full simulation. Fixes issue #57, but it's slightly less efficient, since it has to copy from the GPU memory after each event.

### CODE REVIEW

**Comment by soleti** [comment]
@peter-madigan for some reason I can't add you as a reviewer but I would appreciate if you could take a quick look.

**Comment by chenel** [comment]
Unfortunately the ometimes-empty events of the official "ND-LAr+TMS" simulation seem to be causing a problem here:

```Traceback (most recent call last):                                              
  File "cli/simulate_pixels.py", line 417, in <module>
    fire.Fire(run_simulation)
  File "/usr/local/lib/python3.8/dist-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "cli/simulate_pixels.py", line 380, in run_simulation
    event_id_list_batch = np.concatenate(event_id_list, axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate```

**Comment by soleti** [comment]
Can you try now @chenel?

**Comment by chenel** [comment]
Progress!  I now get through the first 262 events of my ~10K event sample.  Unfortunately I'm running out of memory now on my ~11GB VRAM GPU. :(

I'm going to try on a machine with a better GPU (more VRAM), but I post this here just in case it is evidence something else might be wrong...

**Comment by chenel** [comment]
sad panda.  about 25% through file (event 2634/8581):
```
Traceback (most recent call last):                                              
  File "cli/simulate_pixels.py", line 418, in <module>
    fire.Fire(run_simulation)
  File "/usr/local/lib/python3.8/dist-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "cli/simulate_pixels.py", line 387, in run_simulation
    _, _, last_time = fee.export_to_hdf5(event_id_list_batch,
  File "/gpfs/slac/staas/fs1/g/neutrino/jwolcott/app/larnd-sim/larndsim/fee.py", line 207, in export_to_hdf5
    io_group = detector.MODULE_TO_IO_GROUPS[module_id][io_group-1]
KeyError: 0
```
I don't see any other output for this particular event.

**Comment by peter-madigan** [comment]
Sorry for the slow response - I don't have my computer with me this week, but I'll take a look as soon as I'm back.

**Comment by soleti** [comment]
@chenel can you send me the path of your input file? when it crashes, does the file contains the events simulated so far?

**Comment by chenel** [comment]
(for the record, file was sent via Slack.  there *is* an output file, which is generally healthy, but it's missing the `tracks` product.  apparently that's still being saved at the end.)

**Comment by soleti** [comment]
Ok there was a missing check in the pixel finding algorithm. Now it should work, let me know if it doesn't.

**Comment by chenel** [comment]
Oh, also, I started poking around in the resulting file to see what I could do with it.  I discovered there appear to be no packets with trigger type 7, which I thought was the "event divider" packet type.
```
>>> import h5py
f = h5py.File("/gpfs/slac/staas/fs1/g/neutrino/jwolcott/data/dune/nd/nd-lar-reco/larndsim/neutrino.LArTMSProductionJun23withLArCV.99.larndsim.h5")
>>> packets = f["packets"][:]
>>> np.count_nonzero(packets["trigger_type"] == 7)
0
>>> np.unique(packets["trigger_type"])
array([ 0,  1,  2, 83], dtype=uint8)
```

**Comment by soleti** [comment]
Oops, I forgot to open the file before writing a config, now it should work 🤞

**Comment by chenel** [comment]
Victory at last!  Finished successfully and file seems to be healthy.  🎉 
(I don't understand why there are 21616 packets with `packet_type` of 7---I thought this were supposed to be event boundaries only?---given there are only 10K events in the edep-sim file, but unless it's likely to be evidence that something went wrong in saving, we can move the discussion elsewhere.)

**Comment by soleti** [comment]
Those are trigger packets, not just event dividers, you can have more than one per event. I'll merge this and eventually investigate more.

**Pull request merged**
